---
title: Gabe Kelley
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: hello@gabekelley.com
description: |
  Gabe Kelley is a designer and developer living in Richmond, VA.
baseurl: ''
url: http://gabekelley.com
twitter_username: gabekelley
github_username: gabekelley
markdown: kramdown
