# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Gabe Kelley
email: hello@gabekelley.com
description: > # this means to ignore newlines until "baseurl:"
  Gabe Kelley is a designer and developer living in Richmond, VA.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://gabekelley.com" # the base hostname & protocol for your site
twitter_username: gabekelley
github_username:  gabekelley

# Build settings
markdown: kramdown
